/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Logica.Arbol_splay;
import Logica.ListaSdoble;
import Logica.Nodo;
import Logica.datos;
import Logica.Cliente;
/**
 *
 * @author osboxes
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    private Help _ayuda;
    private Arbol_splay _busquedas;
    private datos _dp;
    private connect _ct;
    private String _mensaje="";
    private Cliente _cl;
    
    public Ventana() {
        _ayuda= new Help();
        _busquedas= new Arbol_splay();
        _dp=new datos();
        _ct=new connect();
        _ct.setDato(_dp);
        _ct.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchInput = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaUrls = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        OPMenu = new javax.swing.JMenu();
        OPConnect = new javax.swing.JMenuItem();
        OPHelp = new javax.swing.JMenu();
        OPOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        SearchInput.setToolTipText("Ingrese el lo que desee buscar");
        getContentPane().add(SearchInput);
        SearchInput.setBounds(240, 60, 450, 35);

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(730, 60, 140, 37);

        ListaUrls.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Instituto Tecnologico de Costa Rica ", "CE-1103", "Sem1-2015", "Proyecto Spider Search Stage 2", "Desarrollado por:", "\t-Gustavo Martines/ 2014098445", "\t-Luis Martinez/2013029940", "\t-Ellioth Ramirez/2014057732" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaUrls);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 140, 860, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/osboxes/NetBeansProjects/SpiderGui/iconoP1.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, -10, 150, 140);

        OPMenu.setText("Options");

        OPConnect.setText("Conectar con servidor");
        OPConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPConnectActionPerformed(evt);
            }
        });
        OPMenu.add(OPConnect);

        OPHelp.setText("Ayuda");
        OPHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPHelpActionPerformed(evt);
            }
        });
        OPMenu.add(OPHelp);

        OPOut.setText("Salir");
        OPOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPOutActionPerformed(evt);
            }
        });
        OPMenu.add(OPOut);

        jMenuBar1.add(OPMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(SearchInput.getText().isEmpty()){
            
        }
        else{
            getTexto();
            search();
            VentanaOpciones listaDeOpciones;
            listaDeOpciones = new VentanaOpciones();
            listaDeOpciones.desplegar();
        }
        //dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void OPConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPConnectActionPerformed
        // TODO add your handling code here:
        _ct.setVisible(true);
    }//GEN-LAST:event_OPConnectActionPerformed

    private void OPHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPHelpActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        _ayuda.setVisible(true);
    }//GEN-LAST:event_OPHelpActionPerformed

    private void OPOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPOutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_OPOutActionPerformed

    private void search() {
        _cl=new Cliente(_dp);
        _cl.start();
        _cl.sendMsg(_mensaje);
        _cl.sendMsg("out");
    }
    
    private void getTexto(){
        ListaSdoble _palabras= new ListaSdoble();
        String contenedor="";
        StringBuilder constructorS= new StringBuilder();
        int y=1;
        for(int x=0; x<=SearchInput.getText().length();x++){
            if(x==SearchInput.getText().length()){
                contenedor=constructorS.toString();
                _palabras.enQueue(contenedor);
                break;
            }
            else if(SearchInput.getText().substring(x,y).equals(" ")){
                contenedor=constructorS.toString();
                _palabras.enQueue(contenedor);
                y++;
                constructorS.delete(0, constructorS.length());
            }
            else{
                constructorS.append(SearchInput.getText().substring(x,y));
                y++;
            }
        }
        insertToTree(_palabras);
    }
    
    private void insertToTree(ListaSdoble pPalabras){
        Nodo tmp =pPalabras.getHead();
        while(tmp!=null){
            if(tmp.getData().compareTo(" ")!=0){
                _busquedas.insert(tmp.getData());
                _mensaje+=(String)tmp.getData();
                if(tmp.getNext()!=null)
                    _mensaje+=",";
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaUrls;
    private javax.swing.JMenuItem OPConnect;
    private javax.swing.JMenu OPHelp;
    private javax.swing.JMenu OPMenu;
    private javax.swing.JMenu OPOut;
    private javax.swing.JTextField SearchInput;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
